# Generated by Django 4.1.3 on 2022-11-05 09:23

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='id',
        ),
        migrations.AddField(
            model_name='blog',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('a5d76874-0e9c-4a30-b310-9031bebd8c05'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='blog',
            name='updated_at',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2022, 11, 5, 9, 23, 50, 197555, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
